name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PLATFORM_TARGET: [thumbv7m-none-eabi, thumbv7em-none-eabihf]

    steps:
      - uses: actions/checkout@v5

      - name: Add Specific Targets
        run: rustup target add ${{ matrix.PLATFORM_TARGET }}

      - name: Build
        run: cargo build --verbose --target ${{ matrix.PLATFORM_TARGET }}
